# Configuration for scrapers

# Careers360 Scraper configuration
careers360_scraper:
  start_page: 1
  end_page: 2

# Graphy Assignment Scraper configuration
graphy_assignment_scraper:
  email: "your_email@example.com"
  password: "your_password"
  assignment_id: "65c5f301e4b051b50cfd6121"
